package ru.stqa.java_avi.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

import java.util.Map;

public class ContactCreationTests extends TestBase {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Test
  public void testContactCreation() {
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(1037, 1040));
    driver.findElement(By.name("user")).
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.xpath("//form[@id=\'LoginForm\']/input[3]")).click();
    driver.findElement(By.linkText("add new")).click();
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("Artur");
    driver.findElement(By.name("lastname")).click();
    driver.findElement(By.name("lastname")).sendKeys("Ivanov");
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("Cherepovets");
    driver.findElement(By.name("mobile")).click();
    driver.findElement(By.name("mobile")).sendKeys("+7985456213");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("av.ivanov@mail.com");
    driver.findElement(By.xpath("//div[@id=\'content\']/form/input[21]")).click();
    driver.findElement(By.linkText("home page")).click();
  }
}
